---
- name: configure server.xml
  template: >
    src=server.xml.j2
    dest={{ tomcat_conf_dir }}/server.xml
    owner=root group={{ tomcat_group }} mode=0640
    validate='xmllint %s'
  notify: restart tomcat

- name: configure logging
  template: >
    src=tomcat-logging.properties.j2
    dest={{ tomcat_conf_dir }}/tomcat-logging.properties
    owner=root group={{ tomcat_group }} mode=0644

- name: configure catalina
  template: >
    src=catalina.properties.j2
    dest={{ tomcat_conf_dir }}/catalina.properties
    owner=root group=root mode=0644
  notify: restart tomcat
  when: tomcat_shared_loader_enabled | bool

- name: write jmxremote.passwd
  copy: >
    content="{{ tomcat_jmx_user }} {{ tomcat_jmx_password }}"
    dest={{ tomcat_conf_dir }}/jmxremote.passwd
    owner=root group={{ tomcat_group }} mode=0640
  notify: restart tomcat
  when: tomcat_jmx_enabled | bool

- name: write jmxremote.access
  copy: >
    content="{{ tomcat_jmx_user }} readwrite"
    dest={{ tomcat_conf_dir }}/jmxremote.access
    owner=root group={{ tomcat_group }} mode=0640
  notify: restart tomcat
  when: tomcat_jmx_enabled | bool

- name: configure shared context
  template: >
    src=context.xml.j2
    dest={{ tomcat_conf_dir }}/context.xml
    owner=root group=root mode=0644
  notify: restart tomcat

- name: link web.xml
  file: >
    src={{ tomcat_home_dir }}/conf/web.xml
    dest={{ tomcat_conf_dir }}/web.xml
    state=link
    force=yes

- name: configure init script
  template: >
    src=runscript.conf.j2
    dest=/etc/conf.d/{{ tomcat_name }}
    owner=root group=root mode=0644
